spring.application.name=usuarios-service
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_Pruebas
spring.datasource.username=postgres
spring.datasource.password=bastian10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

##spring.security.user.name=admin
##spring.security.user.password=1234