spring.application.name=Api-Gateway
server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=usuarios-service
spring.cloud.gateway.server.webmvc.routes[0].uri=${USUARIOS_SERVICE_URL:http://localhost:8084}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/petly/usuarios/**,/petly/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=reportes-service
spring.cloud.gateway.server.webmvc.routes[1].uri=${REPORTES_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/petly/reportes/**

spring.cloud.gateway.server.webmvc.routes[2].id=geolocalizacion-service
spring.cloud.gateway.server.webmvc.routes[2].uri=${GEO_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/petly/geo/**

spring.cloud.gateway.server.webmvc.routes[3].id=mascotas-service
spring.cloud.gateway.server.webmvc.routes[3].uri=${MASCOTAS_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/petly/mascotas/**

spring.cloud.gateway.server.webmvc.routes[5].id=coincidencias-service
spring.cloud.gateway.server.webmvc.routes[5].uri=${COINCIDENCIAS_SERVICE_URL:http://localhost:8085}
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/petly/coincidencias/**

spring.cloud.gateway.server.webmvc.routes[4].id=notificaciones-service
spring.cloud.gateway.server.webmvc.routes[4].uri=${NOTIFICACIONES_SERVICE_URL:http://localhost:8086}
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/petly/notificaciones/**
