spring.application.name=reportes-service
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_Reportes
spring.datasource.username=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true    
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8081

jwt.secret=v5zti3ggthj4radzaynh5q9uoezj66cl
jwt.expiration=3600000

spring.security.user.name=admin
spring.security.user.password=1234

OCI_USER_ID=ocid1.user.oc1..aaaaaaaa7uhovjtovpwbckixajwb5hc2eolju656tajhuouvytpdvglnxpyq
OCI_TENANCY_ID=ocid1.tenancy.oc1..aaaaaaaaqyifudeykwssoesrhgsy3m2yfx7m2wkrclaieq2dzudx4ugblexq
OCI_FINGERPRINT=00:49:4b:f9:fa:bc:c4:bb:43:e5:61:1f:be:23:c0:2d
OCI_REGION=sa-santiago-1

OCI_NAMESPACE=axgfwyf4tpjt
OCI_BUCKET=Mascotas-bucket


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.queue.reporte-nuevo=reporte.nuevo

spring.jackson.serialization.write-dates-as-timestamps=false

# Resilience4j
resilience4j.circuitbreaker.instances.geoService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.geoService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.geoService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.geoService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.geoService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.geoService.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.retry.instances.geoService.maxAttempts=3
resilience4j.retry.instances.geoService.waitDuration=500ms
resilience4j.bulkhead.instances.geoService.maxConcurrentCalls=10
resilience4j.bulkhead.instances.geoService.maxWaitDuration=0

# Timeouts de Feign para geolocalizacion-service
spring.cloud.openfeign.client.config.geolocalizacion-service.connectTimeout=1000
spring.cloud.openfeign.client.config.geolocalizacion-service.readTimeout=2000

# Actuator para monitorear Resilience4j
management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents,retries
management.health.circuitbreakers.enabled=true